### ISSUE TITLE
[Feature]: More description for target version

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1000]
### Package Scope

@suspensive/react-query

### Bug description

<img width="362" alt="image" src="https://github.com/toss/suspensive/assets/61593290/ccc758d2-b35a-4231-9366-107db583e319">

issued by @juno7803

**Comment by manudeli** [comment]
@juno7803 Could you add what you expect?

**Comment by juno7803** [comment]
I believe that the cli for @suspensive/react-query status clearly supports different versions of react-query for users. However, despite its clear functionality, I find the guidance provided by the CLI to be unclear. If it's alright with you, could I contribute by submitting a Pull Request? 😁

**Comment by gwansikk** [comment]
> I believe that the cli for @suspensive/react-query status clearly supports different versions of react-query for users.
> 
> However, despite its clear functionality, I find the guidance provided by the CLI to be unclear. If it's alright with you, could I contribute by submitting a Pull Request? 😁

@juno7803  I agree, especially the `(5)` in `[@suspensive/react-query] v2.3.0 (5)` is not clear. It is difficult for users to understand what it means. Please revise it to provide sufficient guidance from the user's perspective.

**Comment by manudeli** [comment]
## Suggestion
I made example what I expected.

### Suspensive React Query with TanStack Query v4

```text
Suspensive React Query status:
@suspensive/react-query@2.3.0 export @suspensive/react-query-4's interfaces
  - useSuspenseQuery
  - useSuspenseQueries
  - useSuspenseInfiniteQuery
  - queryOptions
  - SuspenseQuery
  - SuspenseQueries
  - SuspenseInfiniteQuery
  - QueryErrorBoundary
@tanstack/react-query@4.36.2
  - all interfaces
```


### Suspensive React Query with TanStack Query v5
```text
Suspensive React Query status:
@suspensive/react-query@2.3.0 export @suspensive/react-query-5's interfaces
  - SuspenseQuery
  - SuspenseQueries
  - SuspenseInfiniteQuery
  - QueryErrorBoundary
@tanstack/react-query@5.32.0
  - useSuspenseQuery
  - useSuspenseQueries
  - useSuspenseInfiniteQuery
  - queryOptions
  - all interfaces
```

**Comment by gwansikk** [comment]
@juno7803 @manudeli 

https://github.com/toss/suspensive/issues/1000#issuecomment-2196488181

Oh, this is really detailed and impressive. However, displaying the list of interfaces might reduce readability if more interfaces are added in the future. Additionally, we would need to update the CLI list every time a new interface is added, which adds to the maintenance workload. How about including a link to the official documentation for information about the interfaces?

**Comment by manudeli** [comment]
> How about including a link to the official documentation for information about the interfaces?

In my opinion, Linking official doc is not good idea to expose what exactly dist/index.js export at each version because official doc only expose latest public apis

So In my opinion, to implement detailed `suspensive-react-query status` Parsing dist/index.js of @suspensive/react-query's exposing package(@suspensive/react-query-4, @suspensive/react-query-5) is good way to expose public apis of each version

> However, displaying the list of interfaces might reduce readability if more interfaces are added in the future.

I agree with your opinion, then how about showing public apis of @suspensive/react-query only, not @tanstack/react-query


### Suspensive React Query with TanStack Query v4

```text
Suspensive React Query status:
@suspensive/react-query@2.3.0 export @suspensive/react-query-4's interfaces
  - useSuspenseQuery
  - useSuspenseQueries
  - useSuspenseInfiniteQuery
  - queryOptions
  - SuspenseQuery
  - SuspenseQueries
  - SuspenseInfiniteQuery
  - QueryErrorBoundary
@tanstack/react-query@4.36.2
```


### Suspensive React Query with TanStack Query v5
```text
Suspensive React Query status:
@suspensive/react-query@2.3.0 export @suspensive/react-query-5's interfaces
  - SuspenseQuery
  - SuspenseQueries
  - SuspenseInfiniteQuery
  - QueryErrorBoundary
@tanstack/react-query@5.32.0
```

**Comment by gwansikk** [comment]
> So In my opinion, to implement detailed suspensive-react-query status Parsing dist/index.js of @suspensive/react-query's exposing package(@suspensive/react-query-4, @suspensive/react-query-5) is good way to expose public apis of each version

@manudeli I agree with your opinion! Is the method you explained the same as the one written below? Do we provide API information by branching according to the version, or do we dynamically display the code exported by `dist/index.cjs` using TypeScript AST?

```ts
if (suspensiveReactQueryVersion === '5') {
  console.log(`
- SuspenseQuery
- SuspenseQueries
- SuspenseInfiniteQuery
- QueryErrorBoundary`)
} else if (suspensiveReactQueryVersion === '4') {
  console.log(`
- useSuspenseQuery
- useSuspenseQueries
- useSuspenseInfiniteQuery
- queryOptions
- SuspenseQuery
- SuspenseQueries
- SuspenseInfiniteQuery
- QueryErrorBoundary`)
}
```

**Comment by manudeli** [comment]
@gwansikk

> Do we provide API information by branching according to the version, or do we dynamically display the code exported by dist/index.cjs using TypeScript AST?

In my opinion, display dynamically finally is better for me. but if we need to resolve this issue first, I think that displaying public apis by branching according to the version statically will be good solution at this first time!

Fast resolve issue, and improving feature gradually also good!

**Comment by juno7803** [comment]
You guys shared a lot of valuable opinions! Thank you so much, and I apologize for the delay.

The biggest inconvenience from the user's perspective was understanding what CLI were trying to convey. Therefore, assuming you know the following key features of `@suspensive/react-query`, it was suggested to show what CLI status supports:
- To use @tanstack/react-query and suspense more effectively
- They can be used together, and even in lower versions(@tanstack/react-query), the latest APIs are provided.

At first, instead of specifying which APIs are provided when using with `@tanstack/react-query v4` and which are provided when using with `@tanstack/react-query v5`, I thought to be sufficient to simply state that v4 provides v5 features and that when upgrading to v5, redundant APIs are maintained as singletons, `@suspensive/react-query` only exporting what is necessary.

However, after reading the new issue comments, I think it's best to be clear as @manudeli mentioned. (Upon reflection, I realize I have some background knowledge from @manudeli 's explanations of the library concept). While I completely agree with @gwansikk's opinion on readability and maintainability, providing document links is also part of maintainability, but personally, I don't prefer navigating through multiple layers (I think that might feel like depth to some people.), especially in CLI.

Therefore, as @manudeli suggested, I think it's best to first resolve the issue by displaying it statically and then improve it through automation. As for how to automate, I might need to study more to contribute as much as those who developed it..!

Thank you once again for sharing your valuable opinions! ❤️
