### ISSUE TITLE
[Feature]: infiniteQueryOptions

### ISSUE THREAD

**Issue by kangju2000** [toss/suspensive#1015]
### Package Scope

@suspensive/react-query-4

### Bug description

I found a type error that occurs when passing the return value of queryOptions as a property to SuspenseInfiniteQuery.

Check it out here: [Codesandbox Link](https://codesandbox.io/p/sandbox/elated-boyd-klqgw6?file=%2Fsrc%2FApp.tsx%3A45%2C1-46%2C1)

### Expected behavior

The return value of queryOptions should be compatible with the props of SuspenseInfiniteQuery without causing any TypeScript errors.

### Possible Solution

If queryOptions cannot adequately handle the infiniteQuery type, we might consider creating a separate infiniteQueryOptions as an alternative approach.

**Comment by manudeli** [comment]
https://github.com/toss/suspensive/pull/1016#issuecomment-2198900615

**Comment by gwansikk** [comment]
It looks like the error is occurring due to type mismatches in `refetchOnMount`, `refetchOnReconnect`, and `refetchOnWindowFocus`. The `queryOptions` are typed as `data: TData`, while in the Infinity Hook, `data: InfiniteData<TData>` should be used.

I agree with both of you that creating `infiniteQueryOptions` to address this is the perfect solution! If this task takes a long time, wrapping it as a temporary measure and gradually updating it could also be a good approach.

**Comment by gwansikk** [comment]
@manudeli I think there might be users currently using this component. How about temporarily wrapping it with the code I suggested and proceeding with `infiniteQueryOptions` in the next version?

like this: https://github.com/toss/suspensive/issues/1015#issuecomment-2199263821

**Comment by manudeli** [comment]
> @manudeli I think there might be users currently using this component. How about temporarily wrapping it with the code I suggested and proceeding with `infiniteQueryOptions` in the next version?
> 
> like this: [#1015 (comment)](https://github.com/toss/suspensive/issues/1015#issuecomment-2199263821)

Cool! Could you make it as Pull Request!? Actually I need this infiniteQueryOptions at now too for my other work
