### ISSUE TITLE
[Feature]: Use 'Toss Product Sans' font

### ISSUE THREAD

**Issue by kangju2000** [toss/suspensive#1144]
### Package Scope

etc

### Description

As Suspensive is joining the Toss organization's library, what do you think about using the `Toss Product Sans` font for the documentation as well?

**Comment by manudeli** [comment]
I want to disagree this. because this project should be standalone with Toss's brand to support all world project not only Toss product. Our role is not representative of Toss. The React team approaches fonts not as a way to brand Facebook, but as a utility for React itself. Fonts imply branding, so I want our docs to be accessible in a purely default font.

**Comment by kangju2000** [comment]
Thank you for your response! I agree with your opinion. Closing the issue.
