### ISSUE TITLE
[Feature] reconstruct Cache, Cacheable, useRead, Read

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1225]
🚀🚀🚀 Let's improve after merging

Below is our imagination with @SEOKKAMONI 
```tsx
// pseudo code below
import { Cache, useRead, Read } from '@suspensive/cache'

const serverCache = new Cache({
  user: (userId: number) => ({
    fn: () => api.user(userId),
    interval: 2000
  }),
  users: () => ({
    fn: () => api.users()
  })
})

const Child = () => {
  const { data: users, invalidate } = useRead(serverCache.users())
  const serverCacheUsers = useRead(serverCache.users())

  serverCacheUsers.invaliate()
  serverCacheUsers.data

  const { data: user } = useRead({
    ...serverCache.user(1),
    interval: 3000 // CacheOptions
  })
  
  Cache.invalidate(serverCache.users())
  Cache.invalidate(serverCache.user(1))

  return (
    <Read {...serverCache.user(1)} interval={2000}>
      {({ data: user }) => user.name}
    </Read>
  )
}
```

_Originally posted by @manudeli in https://github.com/toss/suspensive/pull/1224#pullrequestreview-2247996262_

**Comment by manudeli** [comment]
Related https://github.com/toss/suspensive/issues/1191

**Comment by ojj1123** [comment]
I have some question about `@suspense/cache`.

I don't know the background why this package is made. But after I read [a description on `README.md`](https://github.com/toss/suspensive?tab=readme-ov-file#suspensivecache---) and source code of this package briefly, I was wondering some problem that this package want to solve. Reading source code([Cache.ts](https://github.com/toss/suspensive/blob/fd988fcb5b1f7600b7902cde705793a5be2b9241/packages/cache/src/Cache.ts)), I feel like this read, do something(e.g. invalidate) or managing the lifecycle of cache integrating with `React.suspense`. So what is the difference from roles of `tanstack/query`? Of course, `tanstack/query` have a role of managing server states, but it provides APIs that can manage caches.
I'm just curious!

**Comment by manudeli** [comment]
In my opinion, It would be better that we request @SEOKKAMONI's reply

**Comment by SEOKKAMONI** [comment]
@ojj1123 Compared to  tanstack/query, suspensive/cache doesn’t just stop at caching server state. The future I envision for suspensive/cache is to make it easier to cache not only server state but also various elements like images, DOM, and more, ultimately creating meaningful experiences for users.

Furthermore, tanstack/query is designed for browsers and, as far as I know, does not work in node environments. My goal for for suspensive/cache is to remove the dependency on React and develop it further so that caching can be easy and convenient even in Node environments.

I'm sorry for the delayed response, and thank you so much for your great question!
